### ISSUE TITLE
No chapter is selected when creating toc.

### ISSUE THREAD

**Issue by djangoliv** [e-gor/Reveal.js-TOC-Progress#10]
At creation (pressing 'q'), the table is not updated. Is it possible to have the right chapter selected without having to change of the current slide? 

Thank you very much for your work.

**Comment by e-gor** [comment]
It's a problem I am aware of but could not solve. The thing is that the CSS styles for marking the current page's titles in bold in the TOC are created dynamically at the same time as the TOC, but they are not applied immediately, a page change has to occur for those styles to apply, I do not know why... If you can think of some possible solution and manage to solve it, feel free to make a pull request, I will gladly accept it!

**Comment by Thus0** [comment]
I've only tested this pull request with Reveal.js 4.x but I think it should work with Reveal.js 3.x

**Comment by e-gor** [comment]
Fixed by #22
