### ISSUE TITLE
Problem with latest reveal.js

### ISSUE THREAD

**Issue by bchretien** [e-gor/Reveal.js-TOC-Progress#4]
I tried testing this plugin with reveal.js' current master branch, but there seems to be some errors (e.g. the table of contents is not fully populated).

You can test with [my `toc-progress` branch](https://github.com/bchretien/reveal.js/tree/toc-progress) where I simply added the plugin to reveal.js and modified the default `index.html` to add the ToC. As you can see, only the first few entries are displayed. This seems to be related to nested `<section>` blocks.

![toc_bug](https://cloud.githubusercontent.com/assets/2742231/5962372/bbadbf38-a7e3-11e4-94df-8363017c1687.png)

**Comment by e-gor** [comment]
Fixed, thanks for informing about the bug!

**Comment by bchretien** [comment]
That was quick, thanks! :smile:

One last thing: if we change

```html
<section>
	<section>
		<h2>Vertical Slides</h2>
		<p>Slides can be nested inside of each other.</p>
		...
```
to:
```html
<section>
	<h2>Vertical Slides</h2>
	<section>
		<p>Slides can be nested inside of each other.</p>
		...
```
`Vertical Slides` disappears from the titles (cf. my updated branch).

Before:

![before](https://cloud.githubusercontent.com/assets/2742231/5968790/00014726-a81c-11e4-88f3-da717477f282.png)

After:

![after](https://cloud.githubusercontent.com/assets/2742231/5968791/0355bace-a81c-11e4-83be-37096f3094ba.png)

**Comment by e-gor** [comment]
Well, the code only looks for <title> elements in leaf <section> elements. You can obtain the desired effect with:

```html
<section>
	<section>
		<h2>Vertical Slides</h2>
	</section>
	<section>
		<p>Slides can be nested inside of each other.</p>
		...
```

**Comment by bchretien** [comment]
Well technically, in the following case:

```html
<section>
    <h2>Vertical Slides</h2>
    <section>
        <p>Slides can be nested inside of each other.</p>
        ...
```

`Vertical Slides` is in a `<section>` (just not in a subsection), and adding an extra section actually changes the result (empty slide with just the title).
