### ISSUE TITLE
Issue with scroll feature

### ISSUE THREAD

**Issue by bchretien** [e-gor/Reveal.js-TOC-Progress#7]
After updating reveal.js to the latest release, I noticed that the scroll feature stopped working for me, i.e. it does not scroll, and the latest sections do not appear when they're active. The issue seems to be [this check](https://github.com/e-gor/Reveal.js-TOC-Progress/blob/7b1dae7a2bd56667d542eead505e13745daa9158/plugin/toc-progress/toc-progress.js#L336):

``` javascript
if (window.getComputedStyle(li_element).getPropertyValue('font-weight')=='700')
```

It seems to be working for my project (with a tweaked CSS) when I replace it with:

``` javascript
if (window.getComputedStyle(li_element).getPropertyValue('font-weight')!='normal')
```

If that depends on the style sheets, a more robust way to do this check may need to be found though.

**Comment by blubbsy** [comment]
i have the same issue, but for example it works without problems with Edge, but in chrome i have these problems.

**Comment by rmcrowley2000** [comment]
A few more notes on this issue.  As of the current version of Edge and chrome, the original line  identified as the problem by @bchretien does not work in either.

The following works in Chrome (replace `700` with `bold`):
`if (window.getComputedStyle(li_element).getPropertyValue('font-weight')=='bold')`

The following works in Edge (remove quotes around 700):
`if (window.getComputedStyle(li_element).getPropertyValue('font-weight')==700)`

As I assume the `'700'` is valid in some browser, I'm using the following code in place of the line:
`if (window.getComputedStyle(li_element).getPropertyValue('font-weight')=='bold' || window.getComputedStyle(li_element).getPropertyValue('font-weight')==700 || window.getComputedStyle(li_element).getPropertyValue('font-weight')=='700')`

**Comment by e-gor** [comment]
The `'700'` works in Firefox, which is the browser I use, and if you say that with those other values and the change you propose it works also in Edge and Chrome, I will make the change right away. Thanks!
